export const MSG = {
   // cat
    GET_CAT_SUCCESS: "GET_CAT_SUCCESS",
    GET_CAT_FAILED: "GET_CAT_FAILED",
    CREATE_CAT_SUCCESS: "CREATE_CAT_SUCCESS",
    CREATE_CAT_FAILED: "CREATE_CAT_FAILED",
    UPDATE_CAT_SUCCESS: "UPDATE_CAT_SUCCESS",
    UPDATE_CAT_FAILED: "UPDATE_CAT_FAILED",

    // order
    MAKE_ORDER_FAILED: "MAKE_ORDER_FAILED",
    MAKE_ORDER_SUCCESS: "MAKE_ORDER_SUCCESS",
    PLACE_ORDER_FAILED: "PLACE_ORDER_FAILED",
    PLACE_ORDER_SUCCESS: "PLACE_ORDER_SUCCESS",
    GET_ORDER_DETAIL_FAILED: "GET_ORDER_DETAIL_FAILED",
    GET_ORDER_DETAIL_SUCCESS: "GET_ORDER_DETAIL_SUCCESS",
    GET_PENDING_ORDER_FAILED: "GET_PENDING_ORDER_FAILED",
    GET_PENDING_ORDER_SUCCESS: "GET_PENDING_ORDER_SUCCESS",
    GET_ORDER_STATUS_FAILED: "GET_ORDER_STATUS_FAILED",
    GET_ORDER_STATUS_SUCCESS: "GET_ORDER_STATUS_SUCCESS",
    GET_ORDER_BY_STATUS_FAILED: "GET_ORDER_BY_STATUS_FAILED",
    GET_ORDER_BY_STATUS_SUCCESS: "GET_ORDER_BY_STATUS_SUCCESS",
    CHANGE_ORDER_STATUS_FAILED: "CHANGE_ORDER_STATUS_FAILED",
    CHANGE_ORDER_STATUS_SUCCESS: "CHANGE_ORDER_STATUS_SUCCESS",


    // common
    NOT_VERIFIED: "NOT_VERIFIED",
    INVALID_EMAIL: "INVALID_EMAIL",
    INVALID_EMAIL_OR_PASS: "INVALID_EMAIL_OR_PASS",
    SEND_OTP_FAILED: "SEND_OTP_FAILED",
    SEND_OTP_SUCCESS: "SEND_OTP_SUCCESS",
    EMPTY_OTP: "EMPTY_OTP",
    VERIFY_OTP_FAILED: "VERIFY_OTP_FAILED",
    VERIFY_OTP_SUCCESS: "VERIFY_OTP_SUCCESS",
    LOG_OUT_FAILED: "LOG_OUT_FAILED",
    LOG_OUT_SESSION_FAILED: "LOG_OUT_SESSION_FAILED",
    LOG_OUT_SUCCESS: "LOG_OUT_SUCCESS",
    LOG_IN_FAILED: "LOG_IN_FAILED",
    LOG_IN_SUCCESS: "LOG_IN_SUCCESS",

    // customer
    CUSTOMER_INFO_INVALID: "CUSTOMER_INFO_INVALID",
    UPDATE_CUSTOMER_FAILED: "UPDATE_CUSTOMER_FAILED",
    UPDATE_CUSTOMER_SUCCESS: "UPDATE_CUSTOMER_SUCCESS",

    // product
    GET_PRODUCT_BY_CAT_SUCCESS: "GET_PRODUCT_BY_CAT_SUCCESS",
    GET_PRODUCT_BY_CAT_FAILED: "GET_PRODUCT_BY_CAT_FAILED",
    GET_PRODUCT_SUCCESS: "GET_PRODUCT_SUCCESS",
    GET_PRODUCT_FAILED: "GET_PRODUCT_FAILED",
    GET_PRODUCT_BY_ID_SUCCESS: "GET_PRODUCT_BY_ID_SUCCESS",
    GET_PRODUCT_BY_ID_FAILED: "GET_PRODUCT_BY_ID_FAILED",
    PRODUCT_INFO_INVALID: "PRODUCT_INFO_INVALID",
    CREATE_PRODUCT_SUCCESS: "CREATE_PRODUCT_SUCCESS",
    CREATE_PRODUCT_FAILED: "CREATE_PRODUCT_FAILED",
    UPDATE_PRODUCT_SUCCESS: "UPDATE_PRODUCT_SUCCESS",
    UPDATE_PRODUCT_FAILED: "UPDATE_PRODUCT_FAILED",
    DELETE_PRODUCT_SUCCESS: "DELETE_PRODUCT_SUCCESS",
    DELETE_PRODUCT_FAILED: "DELETE_PRODUCT_FAILED",
    FIND_BY_NAME_PRODUCT_SUCCESS: "FIND_BY_NAME_PRODUCT_SUCCESS",
    FIND_BY_NAME_PRODUCT_FAILED: "FIND_BY_NAME_PRODUCT_FAILED",

    // user
    GET_PROFILE_SUCCESS: "GET_PROFILE_SUCCESS",
    GET_PROFILE_FAILED: "GET_PROFILE_FAILED",
    CHANGE_PASS_SUCCESS: "CHANGE_PASS_SUCCESS",
    CHANGE_PASS_FAILED: "CHANGE_PASS_FAILED",
    SEND_PASS_EMAIL: "SEND_PASS_EMAIL",
    CREATE_USER_SUCCESS: "CREATE_USER_SUCCESS",
    CREATE_USER_FAILED: "CREATE_USER_FAILED",
    UPDATE_USER_SUCCESS: "UPDATE_USER_SUCCESS",
    UPDATE_USER_FAILED: "UPDATE_USER_FAILED",
    DELETE_USER_SUCCESS: "DELETE_USER_SUCCESS",
    DELETE_USER_FAILED: "DELETE_USER_FAILED",


    // supplier
    GET_SUPPLIER_SUCCESS: "GET_SUPPLIER_SUCCESS",
    GET_SUPPLIER_FAILED: "GET_SUPPLIER_FAILED",
    CREATE_SUPPLIER_SUCCESS: "CREATE_SUPPLIER_SUCCESS",
    CREATE_SUPPLIER_FAILED: "CREATE_SUPPLIER_FAILED",
    UPDATE_SUPPLIER_SUCCESS: "UPDATE_SUPPLIER_SUCCESS",
    UPDATE_SUPPLIER_FAILED: "UPDATE_SUPPLIER_FAILED",

    // statistic
    GET_STATISTIC_GENERAL_SUCCESS: "GET_STATISTIC_GENERAL_SUCCESS",
    GET_STATISTIC_GENERAL_FAILED: "GET_STATISTIC_GENERAL_FAILED",
    GET_TOP_PRODUCT_SUCCESS: "GET_TOP_PRODUCT_SUCCESS",
    GET_TOP_PRODUCT_FAILED: "GET_TOP_PRODUCT_FAILED",

}